// actionGetReceiveDistrict
// Created by Man Nguyen
// 19/10/2023

export const GET_RECEIVE_DISTRICT = 'GET_RECEIVE_DISTRICT';
export const GET_RECEIVE_DISTRICT_SUCCESS = 'GET_RECEIVE_DISTRICT_SUCCESS';
export const GET_RECEIVE_DISTRICT_FAILED = 'GET_RECEIVE_DISTRICT_FAILED';
export const RESET_GET_RECEIVE_DISTRICT = 'RESET_GET_RECEIVE_DISTRICT';
