

export const CHECKOUT_VNPAY = 'CHECKOUT_VNPAY';
export const CHECKOUT_VNPAY_SUCCESS = 'CHECKOUT_VNPAY_SUCCESS';
export const CHECKOUT_VNPAY_FAILED = 'CHECKOUT_VNPAY_FAILED';
export const RESET_CHECKOUT_VNPAY = 'RESET_CHECKOUT_VNPAY';
