

export const CHECK_RETURN_VNPAY = 'CHECK_RETURN_VNPAY';
export const CHECK_RETURN_VNPAY_SUCCESS = 'CHECK_RETURN_VNPAY_SUCCESS';
export const CHECK_RETURN_VNPAY_FAILED = 'CHECK_RETURN_VNPAY_FAILED';
export const RESET_CHECK_RETURN_VNPAY = 'RESET_CHECK_RETURN_VNPAY';
