

export const GET_TIME_FLASH_SALE = 'GET_TIME_FLASH_SALE';
export const UPDATE_TIME_FLASH_SALE = 'UPDATE_TIME_FLASH_SALE';
export const GET_TIME_FLASH_SALE_SUCCESS = 'GET_TIME_FLASH_SALE_SUCCESS';
export const GET_TIME_FLASH_SALE_FAILED = 'GET_TIME_FLASH_SALE_FAILED';
export const RESET_GET_TIME_FLASH_SALE = 'RESET_GET_TIME_FLASH_SALE';
