// GET_ORDER_DETAIL
// Created by Man Nguyen
// 29/10/2023

export const GET_ORDER_DETAIL = 'GET_ORDER_DETAIL';
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS';
export const GET_ORDER_DETAIL_FAILED = 'GET_ORDER_DETAIL_FAILED';
export const RESET_GET_ORDER_DETAIL = 'RESET_GET_ORDER_DETAIL';
