

export const UPDATE_FLASH_SALE = 'UPDATE_FLASH_SALE';
export const UPDATE_FLASH_SALE_SUCCESS = 'UPDATE_FLASH_SALE_SUCCESS';
export const UPDATE_FLASH_SALE_FAILED = 'UPDATE_FLASH_SALE_FAILED';
export const RESET_UPDATE_FLASH_SALE = 'RESET_UPDATE_FLASH_SALE';
