export const SEARCH_CUSTOMER = 'SEARCH_CUSTOMER';
export const SEARCH_CUSTOMER_SUCCESS = 'SEARCH_CUSTOMER_SUCCESS';
export const SEARCH_CUSTOMER_FAILED = 'SEARCH_CUSTOMER_FAILED';
export const RESET_SEARCH_CUSTOMER = 'RESET_SEARCH_CUSTOMER';
