// search orders
// Created by Man Nguyen
// 20/10/2023

export const SEARCH_ORDERS = 'SEARCH_ORDERS';
export const SEARCH_ORDERS_SUCCESS = 'SEARCH_ORDERS_SUCCESS';
export const SEARCH_ORDERS_FAILED = 'SEARCH_ORDERS_FAILED';
export const RESET_SEARCH_ORDERS = 'RESET_SEARCH_ORDERS';
