// actionGetAllUsersDelivering
// Created by Hung dev
// 05/11/2023

export const GET_ALL_USERS_DELIVERING = 'GET_ALL_USERS_DELIVERING';
export const GET_ALL_USERS_DELIVERING_SUCCESS = 'GET_ALL_USERS_DELIVERING_SUCCESS';
export const GET_ALL_USERS_DELIVERING_FAILED = 'GET_ALL_USERS_DELIVERING_FAILED';
export const RESET_GET_ALL_USERS_DELIVERING = 'RESET_GET_ALL_USERS_DELIVERING';