

export const UPDATE_TIME_FLASH_SALE = 'UPDATE_TIME_FLASH_SALE';
export const UPDATE_TIME_FLASH_SALE_SUCCESS = 'UPDATE_TIME_FLASH_SALE_SUCCESS';
export const UPDATE_TIME_FLASH_SALE_FAILED = 'UPDATE_TIME_FLASH_SALE_FAILED';
export const RESET_UPDATE_TIME_FLASH_SALE = 'RESET_UPDATE_TIME_FLASH_SALE';
