// actionGetAllUsersRejected
// Created by Hung dev
// 05/11/2023

export const GET_ALL_USERS_REJECTED = 'GET_ALL_USERS_REJECTED';
export const GET_ALL_USERS_REJECTED_SUCCESS = 'GET_ALL_USERS_REJECTED_SUCCESS';
export const GET_ALL_USERS_REJECTED_FAILED = 'GET_ALL_USERS_REJECTED_FAILED';
export const RESET_GET_ALL_USERS_REJECTED = 'RESET_GET_ALL_USERS_REJECTED';