// actionGetAllOrdersCompleted
// Created by Man Nguyen
// 19/10/2023

export const GET_ALL_ORDERS_COMPLETED = 'GET_ALL_ORDERS_COMPLETED';
export const GET_ALL_ORDERS_COMPLETED_SUCCESS = 'GET_ALL_ORDERS_COMPLETED_SUCCESS';
export const GET_ALL_ORDERS_COMPLETED_FAILED = 'GET_ALL_ORDERS_COMPLETED_FAILED';
export const RESET_GET_ALL_ORDERS_COMPLETED = 'RESET_GET_ALL_ORDERS_COMPLETED';
