

export const GET_PHONE_NUMBER = 'GET_PHONE_NUMBER';
export const ADD_PHONE_NUMBER = 'ADD_PHONE_NUMBER';
export const DELETE_PHONE_NUMBER = 'DELETE_PHONE_NUMBER';
export const RESET_PHONE_NUMBER = 'RESET_PHONE_NUMBER';
