// actionGetNumOfOrdersStatus
// Created by Man Nguyen
// 19/10/2023

export const GET_NUM_OF_ORDERS_STATUS = 'GET_NUM_OF_ORDERS_STATUS';
export const GET_NUM_OF_ORDERS_STATUS_SUCCESS = 'GET_NUM_OF_ORDERS_STATUS_SUCCESS';
export const GET_NUM_OF_ORDERS_STATUS_FAILED = 'GET_NUM_OF_ORDERS_STATUS_FAILED';
export const RESET_GET_NUM_OF_ORDERS_STATUS = 'RESET_GET_NUM_OF_ORDERS_STATUS';
