

export const DELETE_ALL_FLASH_SALE = 'DELETE_ALL_FLASH_SALE';
export const DELETE_ALL_FLASH_SALE_SUCCESS = 'DELETE_ALL_FLASH_SALE_SUCCESS';
export const DELETE_ALL_FLASH_SALE_FAILED = 'DELETE_ALL_FLASH_SALE_FAILED';
export const RESET_DELETE_ALL_FLASH_SALE = 'RESET_DELETE_ALL_FLASH_SALE';
