// actionGetAllUsersCanceled
// Created by Hung dev
// 05/11/2023

export const GET_ALL_USERS_CANCELED = 'GET_ALL_USERS_CANCELED';
export const GET_ALL_USERS_CANCELED_SUCCESS = 'GET_ALL_USERS_CANCELED_SUCCESS';
export const GET_ALL_USERS_CANCELED_FAILED = 'GET_ALL_USERS_CANCELED_FAILED';
export const RESET_GET_ALL_USERS_CANCELED = 'RESET_GET_ALL_USERS_CANCELED';