// actionGetAllUsersCompleted
// Created by Hung dev
// 05/11/2023

export const GET_ALL_USERS_COMPLETED = 'GET_ALL_USERS_COMPLETED';
export const GET_ALL_USERS_COMPLETED_SUCCESS = 'GET_ALL_USERS_COMPLETED_SUCCESS';
export const GET_ALL_USERS_COMPLETED_FAILED = 'GET_ALL_USERS_COMPLETED_FAILED';
export const RESET_GET_ALL_USERS_COMPLETED = 'RESET_GET_ALL_USERS_COMPLETED';