

export const GET_SHIPPING_FEE = 'GET_SHIPPING_FEE';
export const GET_SHIPPING_FEE_SUCCESS = 'GET_SHIPPING_FEE_SUCCESS';
export const GET_SHIPPING_FEE_FAILED = 'GET_SHIPPING_FEE_FAILED';
export const RESET_GET_SHIPPING_FEE = 'RESET_GET_SHIPPING_FEE';
