

export const CHECK_IPN_VNPAY = 'CHECK_IPN_VNPAY';
export const CHECK_IPN_VNPAY_SUCCESS = 'CHECK_IPN_VNPAY_SUCCESS';
export const CHECK_IPN_VNPAY_FAILED = 'CHECK_IPN_VNPAY_FAILED';
export const RESET_CHECK_IPN_VNPAY = 'RESET_CHECK_IPN_VNPAY';
