// actionGetReceiveWard
// Created by Man Nguyen
// 19/10/2023

export const GET_RECEIVE_WARD = 'GET_RECEIVE_WARD';
export const GET_RECEIVE_WARD_SUCCESS = 'GET_RECEIVE_WARD_SUCCESS';
export const GET_RECEIVE_WARD_FAILED = 'GET_RECEIVE_WARD_FAILED';
export const RESET_GET_RECEIVE_WARD = 'RESET_GET_RECEIVE_WARD';
