

export const CREATE_CUSTOMER_ORDER = 'CREATE_CUSTOMER_ORDER';
export const CREATE_CUSTOMER_ORDER_SUCCESS = 'CREATE_CUSTOMER_ORDER_SUCCESS';
export const CREATE_CUSTOMER_ORDER_FAILED = 'CREATE_CUSTOMER_ORDER_FAILED';
export const RESET_CREATE_CUSTOMER_ORDER = 'RESET_CREATE_CUSTOMER_ORDER';
