

export const GET_RECEIVE_PROVINCE = 'GET_RECEIVE_PROVINCE';
export const GET_RECEIVE_PROVINCE_SUCCESS = 'GET_RECEIVE_PROVINCE_SUCCESS';
export const GET_RECEIVE_PROVINCE_FAILED = 'GET_RECEIVE_PROVINCE_FAILED';
export const RESET_GET_RECEIVE_PROVINCE = 'RESET_GET_RECEIVE_PROVINCE';
