

export const GET_ORDER_DETAILS = 'GET_ORDER_DETAILS';
export const ADD_PRODUCT_TO_ORDER_DETAILS = 'ADD_PRODUCT_TO_ORDER_DETAILS';
export const INCREASE_PRODUCT_ON_ORDER_DETAILS = 'INCREASE_PRODUCT_ON_ORDER_DETAILS';
export const DELETE_PRODUCT_FROM_ORDER_DETAILS = 'DELETE_PRODUCT_FROM_ORDER_DETAILS';
export const RESET_ORDER_DETAILS = 'RESET_ORDER_DETAILS';
