// actionGetAllOrdersWaiting
// Created by Man Nguyen
// 19/10/2023

export const GET_ALL_ORDERS_WAITING = 'GET_ALL_ORDERS_WAITING';
export const GET_ALL_ORDERS_WAITING_SUCCESS = 'GET_ALL_ORDERS_WAITING_SUCCESS';
export const GET_ALL_ORDERS_WAITING_FAILED = 'GET_ALL_ORDERS_WAITING_FAILED';
export const RESET_GET_ALL_ORDERS_WAITING = 'RESET_GET_ALL_ORDERS_WAITING';
