// actionGetAllOrdersDelivering
// Created by Man Nguyen
// 19/10/2023

export const GET_ALL_ORDERS_DELIVERING = 'GET_ALL_ORDERS_DELIVERING';
export const GET_ALL_ORDERS_DELIVERING_SUCCESS = 'GET_ALL_ORDERS_DELIVERING_SUCCESS';
export const GET_ALL_ORDERS_DELIVERING_FAILED = 'GET_ALL_ORDERS_DELIVERING_FAILED';
export const RESET_GET_ALL_ORDERS_DELIVERING = 'RESET_GET_ALL_ORDERS_DELIVERING';
