// actionGetAllUsersWaiting
// Created by Hung dev
// 05/11/2023

export const GET_ALL_USERS_WAITING = 'GET_ALL_USERS_WAITING';
export const GET_ALL_USERS_WAITING_SUCCESS = 'GET_ALL_USERS_WAITING_SUCCESS';
export const GET_ALL_USERS_WAITING_FAILED = 'GET_ALL_USERS_WAITING_FAILED';
export const RESET_GET_ALL_USERS_WAITING = 'RESET_GET_ALL_USERS_WAITING';