

export const GET_FLASH_SALE_DETAILS = 'GET_FLASH_SALE_DETAILS';
export const GET_FLASH_SALE_DETAILS_SUCCESS = 'GET_FLASH_SALE_DETAILS_SUCCESS';
export const GET_FLASH_SALE_DETAILS_FAILED = 'GET_FLASH_SALE_DETAILS_FAILED';
export const ADD_PRODUCT_TO_FLASH_SALE_DETAILS = 'ADD_PRODUCT_TO_FLASH_SALE_DETAILS';
export const CHANGE_STOCK_ON_FLASH_SALE_DETAILS = 'CHANGE_STOCK_ON_FLASH_SALE_DETAILS';
export const CHANGE_DISCOUNT_ON_FLASH_SALE_DETAILS = 'CHANGE_DISCOUNT_ON_FLASH_SALE_DETAILS';
export const DELETE_PRODUCT_FROM_FLASH_SALE_DETAILS = 'DELETE_PRODUCT_FROM_FLASH_SALE_DETAILS';
export const RESET_FLASH_SALE_DETAILS = 'RESET_FLASH_SALE_DETAILS';
