// actionGetAllOrdersRejected
// Created by Man Nguyen
// 19/10/2023

export const GET_ALL_ORDERS_REJECTED = 'GET_ALL_ORDERS_REJECTED';
export const GET_ALL_ORDERS_REJECTED_SUCCESS = 'GET_ALL_ORDERS_REJECTED_SUCCESS';
export const GET_ALL_ORDERS_REJECTED_FAILED = 'GET_ALL_ORDERS_REJECTED_FAILED';
export const RESET_GET_ALL_ORDERS_REJECTED = 'RESET_GET_ALL_ORDERS_REJECTED';
