export const GET_ALL_ORDERS_CANCELED = 'GET_ALL_ORDERS_CANCELED';
export const GET_ALL_ORDERS_CANCELED_SUCCESS = 'GET_ALL_ORDERS_CANCELED_SUCCESS';
export const GET_ALL_ORDERS_CANCELED_FAILED = 'GET_ALL_ORDERS_CANCELED_FAILED';
export const RESET_GET_ALL_ORDERS_CANCELED = 'RESET_GET_ALL_ORDERS_CANCELED';
